version: '3.8'
services:
  mongodb:
    image: mongo:latest
    container_name: mongodb
    ports:
      - "27018:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - app_network

  backend:
    image: "node:22.15.0-alpine3.20"
    container_name: backend
    working_dir: /app/backend
    volumes:
      - .:/app
    ports:
      - "5000:5000"
    command: "npm start"
    environment:
      PORT: 5000
      MONGO_URI: mongodb://@mongodb:27017/urlshortener
    depends_on:
      - mongodb
    networks:
      - app_network

  frontend:
    image: "node:22.15.0-alpine3.20"
    container_name: frontend
    working_dir: /app/frontend
    ports:
      - "3000:3000"
    environment:
      NEXT_PUBLIC_BACKEND_URL: http://backend:5000
        NODE_ENV=development
    volumes:
      - ./frontend:/app 
      - /app/node_modules 
    command: sh -c "npm install && npm run dev"
    depends_on:
      - backend
    networks:
      - app_network


  prometheus:
    image: prom/prometheus:latest
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus.yml:/etc/prometheus/prometheus.yml:ro
    depends_on:
      - backend
    networks:
      - app_network

  grafana:
    image: grafana/grafana:latest
    container_name: grafana
    ports:
      - "3002:3000"
    environment:
      GF_SECURITY_ADMIN_USER: admin
      GF_SECURITY_ADMIN_PASSWORD: 123456
    depends_on:
      - prometheus
    networks:
      - app_network

  node-exporter:
    image: prom/node-exporter:latest
    container_name: node-exporter
    ports:
      - "9100:9100"
    networks:
      - app_network
    volumes:
      - /proc:/host/proc:ro
      - /sys:/host/sys:ro
      - /:/rootfs:ro
    command:
      - '--path.procfs=/host/proc'
      - '--path.sysfs=/host/sys'
      - '--collector.filesystem.ignored-mount-points'
      - '^/(sys|proc|dev|host|etc)($$|/)'

networks:
  app_network:
    driver: bridge

volumes:
  mongo_data: